import { Router, type IRouter } from "express";
import healthRouter from "./health";
import metaRouter from "./meta";
import authRouter from "./auth";
import meRouter from "./me";
import dashboardRouter from "./dashboard";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import teamsRouter from "./teams";
import jobTitlesRouter from "./job-titles";
import employeesRouter from "./employees";
import hrDocumentsRouter from "./hr-documents";
import internshipsRouter from "./internships";
import idCardsRouter from "./id-cards";
import credentialsRouter from "./credentials";
import publicVerifyRouter from "./public-verify";
import idCardPublicRouter from "./id-card-public";
import financeRouter from "./finance";
import clientsRouter from "./clients";
import serviceTicketsRouter from "./service-tickets";
import approvalsRouter from "./approvals";
import reportsRouter from "./reports";
import channelsRouter from "./channels";
import calendarRouter from "./calendar";
import activityRouter from "./activity";
import notesRouter from "./notes";
import pushTokensRouter from "./push-tokens";
import aiRouter from "./ai";

const router: IRouter = Router();

router.use(publicVerifyRouter);
router.use(idCardPublicRouter);
router.use(healthRouter);
router.use(metaRouter);
router.use(authRouter);
router.use(meRouter);
router.use(dashboardRouter);
router.use(projectsRouter);
router.use(tasksRouter);
router.use(teamsRouter);
router.use(jobTitlesRouter);
router.use(employeesRouter);
router.use(hrDocumentsRouter);
router.use(internshipsRouter);
router.use(idCardsRouter);
router.use(credentialsRouter);
router.use(financeRouter);
router.use(clientsRouter);
router.use(serviceTicketsRouter);
router.use(approvalsRouter);
router.use(reportsRouter);
router.use(channelsRouter);
router.use(calendarRouter);
router.use(activityRouter);
router.use(notesRouter);
router.use(pushTokensRouter);
router.use(aiRouter);

export default router;
